# Generated by Django 6.0.1 on 2026-01-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.JSONField(default=dict, help_text='{"ky": "Консультацияга жазылуу", "ru": "Запись на консультацию", "en": "Book a consultation"}', verbose_name='Заголовок формы')),
                ('form_description', models.JSONField(default=dict, help_text='{"ky": "...", "ru": "...", "en": "..."}', verbose_name='Описание формы')),
                ('label_name', models.JSONField(default=dict, help_text='{"ky": "Аты-жөнү", "ru": "Имя", "en": "Name"}', verbose_name='Label: Имя')),
                ('label_email', models.JSONField(default=dict, help_text='{"ky": "Email", "ru": "Email", "en": "Email"}', verbose_name='Label: Email')),
                ('label_topic', models.JSONField(default=dict, help_text='{"ky": "Тема", "ru": "Тема", "en": "Topic"}', verbose_name='Label: Тема')),
                ('label_message', models.JSONField(default=dict, help_text='{"ky": "Билдирүү", "ru": "Сообщение", "en": "Message"}', verbose_name='Label: Сообщение')),
                ('placeholder_name', models.JSONField(default=dict, help_text='{"ky": "Аты-жөнүңүздү жазыңыз", "ru": "Введите ваше имя", "en": "Enter your name"}', verbose_name='Placeholder: Имя')),
                ('placeholder_email', models.JSONField(default=dict, help_text='{"ky": "example@mail.com", "ru": "example@mail.com", "en": "example@mail.com"}', verbose_name='Placeholder: Email')),
                ('placeholder_topic', models.JSONField(default=dict, help_text='{"ky": "Тема", "ru": "Тема", "en": "Topic"}', verbose_name='Placeholder: Тема')),
                ('placeholder_message', models.JSONField(default=dict, help_text='{"ky": "Билдирүүңүздү жазыңыз", "ru": "Напишите ваше сообщение", "en": "Write your message"}', verbose_name='Placeholder: Сообщение')),
                ('submit_button_text', models.JSONField(default=dict, help_text='{"ky": "Жөнөтүү", "ru": "Отправить", "en": "Send"}', verbose_name='Текст кнопки отправки')),
                ('success_message', models.JSONField(default=dict, help_text='{"ky": "Билдирүүңүз ийгиликтүү жөнөтүлдү!", "ru": "Ваше сообщение успешно отправлено!", "en": "Your message has been sent successfully!"}', verbose_name='Сообщение об успехе')),
                ('error_message', models.JSONField(default=dict, help_text='{"ky": "Ката кетти", "ru": "Произошла ошибка", "en": "An error occurred"}', verbose_name='Сообщение об ошибке')),
                ('validation_name_min_length', models.JSONField(default=dict, help_text='{"ky": "Аты-жөнү 2 символдон кем болбошу керек", "ru": "Имя не может быть короче 2 символов", "en": "Name must be at least 2 characters"}', verbose_name='Ошибка: имя слишком короткое')),
                ('validation_message_min_length', models.JSONField(default=dict, help_text='{"ky": "Билдирүү өтө кыска", "ru": "Сообщение слишком короткое", "en": "Message is too short"}', verbose_name='Ошибка: сообщение слишком короткое')),
                ('validation_email_invalid', models.JSONField(default=dict, help_text='{"ky": "Email туура эмес", "ru": "Email некорректен", "en": "Invalid email"}', verbose_name='Ошибка: невалидный email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Конфигурация формы обратной связи',
                'verbose_name_plural': 'Конфигурация формы обратной связи',
            },
        ),
    ]
