# Generated by Django 6.0.1 on 2026-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactformconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformconfig',
            name='label_email',
        ),
        migrations.RemoveField(
            model_name='contactformconfig',
            name='label_topic',
        ),
        migrations.RemoveField(
            model_name='contactformconfig',
            name='placeholder_email',
        ),
        migrations.RemoveField(
            model_name='contactformconfig',
            name='placeholder_topic',
        ),
        migrations.RemoveField(
            model_name='contactformconfig',
            name='validation_email_invalid',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='topic',
        ),
        migrations.AddField(
            model_name='contactformconfig',
            name='faculty_options',
            field=models.JSONField(default=list, verbose_name='Опции факультетов'),
        ),
        migrations.AddField(
            model_name='contactformconfig',
            name='label_faculty',
            field=models.JSONField(default=dict, verbose_name='Label: Факультет'),
        ),
        migrations.AddField(
            model_name='contactformconfig',
            name='label_phone',
            field=models.JSONField(default=dict, verbose_name='Label: Телефон'),
        ),
        migrations.AddField(
            model_name='contactformconfig',
            name='placeholder_faculty',
            field=models.JSONField(default=dict, verbose_name='Placeholder: Факультет'),
        ),
        migrations.AddField(
            model_name='contactformconfig',
            name='placeholder_phone',
            field=models.JSONField(default=dict, verbose_name='Placeholder: Телефон'),
        ),
        migrations.AddField(
            model_name='contactformconfig',
            name='validation_faculty_required',
            field=models.JSONField(default=dict, verbose_name='Ошибка: факультет обязателен'),
        ),
        migrations.AddField(
            model_name='contactformconfig',
            name='validation_phone_invalid',
            field=models.JSONField(default=dict, verbose_name='Ошибка: невалидный телефон'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='faculty',
            field=models.CharField(default='', max_length=100, verbose_name='Факультет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='error_message',
            field=models.JSONField(default=dict, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='form_description',
            field=models.JSONField(default=dict, verbose_name='Описание формы'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='form_title',
            field=models.JSONField(default=dict, verbose_name='Заголовок формы'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='label_message',
            field=models.JSONField(default=dict, verbose_name='Label: Примечание'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='label_name',
            field=models.JSONField(default=dict, verbose_name='Label: Имя'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='placeholder_message',
            field=models.JSONField(default=dict, verbose_name='Placeholder: Примечание'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='placeholder_name',
            field=models.JSONField(default=dict, verbose_name='Placeholder: Имя'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='submit_button_text',
            field=models.JSONField(default=dict, verbose_name='Текст кнопки отправки'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='success_message',
            field=models.JSONField(default=dict, verbose_name='Сообщение об успехе'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='validation_message_min_length',
            field=models.JSONField(default=dict, verbose_name='Ошибка: сообщение слишком короткое'),
        ),
        migrations.AlterField(
            model_name='contactformconfig',
            name='validation_name_min_length',
            field=models.JSONField(default=dict, verbose_name='Ошибка: имя слишком короткое'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Примечание'),
        ),
    ]
