# Generated by Django 6.0.1 on 2026-01-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='hero_image',
            field=models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='lead',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
