# Generated by Django 6.0.1 on 2026-01-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_hero_image_alter_newstranslation_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstranslation',
            name='slug',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
