# Generated by Django 6.0.1 on 2026-01-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newstranslation_slug_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d', verbose_name='Изображения'),
        ),
    ]
