# Generated by Django 6.0.1 on 2026-01-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AlterField(
            model_name='news',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d', verbose_name='Главное изображения'),
        ),
        migrations.DeleteModel(
            name='NewsTranslation',
        ),
    ]
