# Generated by Django 6.0.1 on 2026-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_slug_alter_news_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.JSONField(default=dict, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='lead',
            field=models.JSONField(blank=True, default=dict, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description',
            field=models.JSONField(blank=True, default=dict, verbose_name='SEO Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title',
            field=models.JSONField(blank=True, default=dict, verbose_name='SEO Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.JSONField(default=dict, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.JSONField(default=dict, verbose_name='Заголовок'),
        ),
    ]
